Update to leptos 0.7.x
bbstilson/leptos_heroicons pull request #6
Opened 2024-12-01 15:46 UTC by stefanboere

Updates this repo to support leptos 0.7.

Needed changes are:

- Remove class attribute (replaced by new attribute-spreading API)
- Rename create_signal to signal
- Use new leptos::prelude::* import
- Increase version
- Type erasure and view types in example

I'll keep it as draft now, these changes should work (and the examples compile), but I'll test on my main leptos repo also to be sure. Probably will do this somewhere this week or next week.

2024-12-07 18:00 UTC, stefanboere commented
For the class you now need the 0.7 spread syntax, I've put this in the README now. But then it also nicely solves #1.

2024-12-09 21:51 UTC, opeolluwa commented
Well done @stefanboere ! 

I was just going to check this out and build it. I hope @bbstilson merge sooner

2024-12-10 20:17 UTC, opeolluwa commented
> Well done @stefanboere !
> 
> I was just going to check this out and build it. I hope @bbstilson merge sooner

@stefanboere Is the update complete, I think I'd rather add the crate as a git dependency

2024-12-10 21:17 UTC, stefanboere commented
@opeolluwa yes it is complete, just waiting on review by bbstilson, whenever he has time :).

2024-12-10 22:26 UTC, opeolluwa commented
> @opeolluwa yes it is complete, just waiting on review by bbstilson, whenever he has time :).

Alright thanks, and well done!

<3

2024-12-10 23:06 UTC, opeolluwa commented
> > Well done @stefanboere !
> > I was just going to check this out and build it. I hope @bbstilson merge sooner
> 
> @stefanboere Is the update complete, I think I'd rather add the crate as a git dependency

I'm getting this error, I think nightly channel is used somewhere up the dependency tree. Did you try it out @stefanboere ? 

<img width="554" alt="Screenshot 2024-12-11 at 00 02 21" src="https://github.com/user-attachments/assets/7684dbfd-d107-4329-a06c-78c516c08b5b">

2024-12-11 17:15 UTC, stefanboere commented
@bbstilson Added few additions by @opeolluwa. Thanks @opeolluwa !

2025-07-28 06:10 UTC, bbstilson requested changes
Apologies for the extraordinary delay. 

I haven't had the bandwidth to keep up with leptos. The changes largely seem okay. I noticed a couple issues. If we get those fixed, I'm happy to merge.

2025-07-28 06:10 UTC, bbstilson commented on generate_components/src/main.rs
> -    let svg = re.replace(svg, "<svg class=class ");
Without this, the class prop doesn't get passed to the generated components.

2025-07-28 06:10 UTC, bbstilson commented on example/src/main.rs
> +    let (active_icon_type, set_icon_type) = signal(IconType::Solid);
With this change, the example doesn't compile. It seems we need to call `.get()` on the uses of `active_icon_type`

2025-07-28 10:13 UTC, stefanboere commented on generate_components/src/main.rs
> -    let svg = re.replace(svg, "<svg class=class ");
Thanks! Class prop didn't work indeed at first

2025-07-28 10:17 UTC, stefanboere commented
Also I saw 'update to leptos 0.8.x' was included, but I'll make a separate tiny PR for that. 

Of course no problem for the delay at all. I've changed according to your comments and regenerated the files. It is ready for reaview again.

2025-07-28 15:09 UTC, merged

2025-07-28 15:10 UTC, bbstilson commented
@stefanboere merged. Thank you again for the patience. I will do my best to be more on top of this repo 🫡